[workspace]
git_only = true
release_always = false
semver_check = false

[[package]]
name = "payg"
version_group = "payg"
git_tag_name = "v{{ version }}"
changelog_path = "CHANGELOG.md"
changelog_include = ["payg-cli"]

[[package]]
name = "payg-cli"
version_group = "payg"
git_tag_enable = false
git_release_enable = false
changelog_update = false

[changelog]
sort_commits = "oldest"
protect_breaking_commits = true
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^docs", group = "Documentation" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactoring" },
  { message = "^test", group = "Testing" },
  { message = "^ci", skip = true },
  { message = "^chore", skip = true },
  { message = "^style", skip = true },
  { message = "^revert", group = "Reverted" },
]
